version: "3.8"

services:
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    ports:
      - "8090:8090"
      - "8000:8000"

networks:
  network:
    driver: bridge