version: "3.8"
services:
  database:
    image: postgres:${POSTGRES_VERSION-13}
    container_name: postgres
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data

