x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  dojo:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:-release-alpine}
    image: danijelradakovic/dojo:${VERSION:-latest}
    restart: on-failure
    ports:
      - "8999:8080"
    networks:
      - dojo
      - monitoring
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}
    logging: *fluent-bit
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:${POSTGRES_VERSION-13}
    restart: always
    networks:
      - dojo
      - monitoring
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      retries: 3
      interval: 5s
      timeout: 5s
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging: *fluent-bit

  pgadmin:
    image: dpage/pgadmin4:8
    networks:
      - dojo
      - monitoring
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PUBLISHED_PORT-8081}:80"
    logging: *fluent-bit
    depends_on:
      - database

volumes:
  database-data:
    name: server-database
  pgadmin:
    name: pgadmin

networks:
  dojo:
    name: dojo
    driver: bridge
  monitoring:
    external: true
