version: '3'
services:
  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250" 
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1"
    volumes:
      - ./consul:/consul/data
  app:
    build: .
    restart: always
    ports:
      - "8090:8090"
      - "8080:8080"
    depends_on:
      - consul
    environment:
      - JAEGER_SERVICE_NAME=posts
      - JAEGER_AGENT_HOST=tracing
      - JAEGER_AGENT_PORT=6831     
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - DB=consul
      - DBPORT=8500
volumes:
  consul:
