services:
  loki:
    image: grafana/loki:main-5206e3a
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.5.3
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

  renderer:
    image: grafana/grafana-image-renderer:3.10.5
    environment:
      ENABLE_METRICS: "true"
    networks:
      - monitoring

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - "9000:16686"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.35.0
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/var/lib/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.1.2
    ports:
      - "9100:9100"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring


volumes:
  grafana:
    name: grafana
  prometheus:
    name: prometheus

networks:
  monitoring:
    name: monitoring
